[package]
name = "ecis"
version = "0.1.0"
edition = "2018"
author = "Chad Baxter <cbax@doslabelectronics.com>"

[dependencies]
barcoders = "1.0.2"
dotenv = "0.15.0"
rocket = "0.5.0-rc.1"
rust-argon2 = "0.8"