[package]
name = "ecis"
version = "0.1.0"
edition = "2018"
author = "Chad Baxter <cbax@doslabelectronics.com>"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"